# Generated by Django 4.2.3 on 2023-08-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0002_channel_uid"),
    ]

    operations = [
        migrations.CreateModel(
            name="roomMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("uid", models.CharField(max_length=200)),
                ("room_name", models.CharField(max_length=200)),
            ],
        ),
    ]
