# Generated by Django 4.2.3 on 2023-08-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_alter_message_options_remove_message_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(),
        ),
    ]
