# Generated by Django 4.2.3 on 2023-08-04 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0003_alter_message_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-updated", "-created"]},
        ),
    ]
