# Generated by Django 4.2.3 on 2023-08-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="premium",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
