# Generated by Django 4.2.3 on 2023-07-31 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="newuser",
            managers=[],
        ),
    ]
