# Generated by Django 4.2.3 on 2023-07-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_newuser_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="fav_books",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
