# Generated by Django 4.2.3 on 2023-07-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_newuser_fav_books"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="user_profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile"),
        ),
    ]
