# Generated by Django 4.2.3 on 2023-07-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_newuser_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="user_profile_image",
            field=models.ImageField(default="deafult.svg", upload_to="profile"),
        ),
    ]
