# Generated by Django 4.2.3 on 2023-08-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_newuser_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="fav_books",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
