# Generated by Django 4.2.3 on 2023-08-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_newuser_fav_books"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="payment",
            field=models.BooleanField(default=False),
        ),
    ]
